server:
  port: 8201
#  tomcat:
#    connection-timeout: 600000

spring:
  profiles:
    active: dev
  # 服务名
  application:
    name: service-cmn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: password
  #设置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis缓存
  redis:
    host: 192.168.199.133
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  #nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis-plus:
#  mapper-locations: classpath:com/wyp/yygh/hosp/mapper/xml/*.xml
#  mapper-locations: classpath:mapper/*.xml