server:
  port: 8203

# 服务名
spring:
  application:
    name: service-mail
  #设置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis缓存
  redis:
    host: 192.168.199.133
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  #nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848
  mail:
    username: 751257261@qq.com
    password: uvgqcnmeqyfibdha
    host: smtp.qq.com
    properties:
      mail:
        smtl:
          ssl:
            enable: true
  #rabbitmq地址
  rabbitmq:
    host: 192.168.199.133
    port: 5672
    username: guest
    password: guest
