server:
  port: 8150

# 服务名
spring:
  application:
    name: service-user
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: password
  #设置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis缓存
  redis:
    host: 192.168.199.133
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  #nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:com/wyp/yygh/user/mapper/xml/*.xml
#  mapper-locations: classpath:mapper/*.xml


wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://guli.shop/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000

