server:
  port: 8207

# 服务名
spring:
  application:
    name: service-task
  profiles:
    active: dev
  #设置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848
  #rabbitmq地址
  rabbitmq:
    host: 192.168.199.133
    port: 5672
    username: guest
    password: guest
