server:
  port: 8206

# 服务名
spring:
  application:
    name: service-oss
  #设置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848

#  阿里云accessKey
aliyun:
  oss:
    accessKeyId: ？？
    secret: ？？
    bucket: yygh-image
    endpoint: oss-cn-beijing.aliyuncs.com
